name: CI
on:
  - push
  - pull_request
jobs:
  build:
    name: Build, lint, and test on Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18
          - 16
          - 14

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test --ci --coverage --maxWorkers=2

      - name: Build
        run: npm run build
